<p>This is <b>about</b> page. 


<p>  Technology Enthusiast focused on software development, designing and implementing the Enterprise Data Services and test automation solutions demonstrated history of working in the Financial Technology Domain. 

Keen To Learn New Skills  I have Enthusiasm for Cloud Computing.
Providing solutions with best-practices with AWS & Azure.
Working knowledge of cloud services: SaaS, PaaS, and IaaS.
In-depth knowledge and experience with Amazon Web Services (AWS). Working knowledge of Multi-tier architectures: load balancers, caching, web servers, application servers, and databases.
Experience with container technologies like Docker, Kubernetes, ECS, EKS. 
Experience with GitHub & Open Source.
Experience with building CI/CD pipeline. </p>
